package thowl.wiprojekt.entity;

import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import thowl.wiprojekt.objects.ChatType;

/**
 * This class specifies the information for a Chat.
 * The annotation @Entity indicates that this is a JPA entity class.
 * The annotation @Table specifies the table name in the database to which this entity refers.
 * The annotation @GeneratedValue indicates that the primary key is generated automatically.
 * The annotation @Id indicates that the id field is the primary key of the table.
 * The annotations @Getter and @Setter generate the getter and setter methods.
 * The annotation @ManyToMany specifies that field is the foreign key of the table.
 * @Author Luca Hüpping
 */
@Entity
@Getter
@Setter
@Table(name = "chat")
public class Chat {

    // ID that is being generated by JPA for every Chat. Every ID is unique.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // String value to give the Chat Entity a Name.
    @Column(name = "chatName", nullable = false)
    private String chatName;

    // String value to give the Chat a theme.
    @Column(name = "theme")
    private String theme;

    // Enum to determine the chat Type.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ChatType chatType;

    // Relation to Messages which are part of the Chat.
    @ManyToMany
    Set<Message> message;

    // Relation to Users who are part of the Chat.
    @ManyToMany
    Set<User> users;

}
