MERGE INTO USERS AS target
    USING (SELECT -1 AS ID, NULL AS USERNAME, NULL AS PASSWORD, NULL AS EMAIL,
                  FALSE AS DARK_MODE, FALSE AS DE_EN, FALSE AS CONTRAST,
                  0 AS FONT_SIZE, FALSE AS EYE_TRACKING,
                  0 AS COLOR_BLINDNESS, FALSE AS SIGN_LANGUAGE,
                  'ANONYMOUS' AS ROLE, 0 AS LEARNINGTYPE_VISUAL, 0 AS LEARNINGTYPE_AURAL,
                  0 AS LEARNINGTYPE_KINESTHETIC, 0 AS LEARNINGTYPE_READWRITE) AS source
    ON target.ID = source.ID
    WHEN MATCHED THEN
        UPDATE SET target.USERNAME = source.USERNAME,
            target.PASSWORD = source.PASSWORD,
            target.EMAIL = source.EMAIL,
            target.DARK_MODE = source.DARK_MODE,
            target.DE_EN = source.DE_EN,
            target.CONTRAST = source.CONTRAST,
            target.FONT_SIZE = source.FONT_SIZE,
            target.EYE_TRACKING = source.EYE_TRACKING,
            target.COLOR_BLINDNESS = source.COLOR_BLINDNESS,
            target.SIGN_LANGUAGE = source.SIGN_LANGUAGE,
            target.ROLE = source.ROLE,
            target.LEARNINGTYPE_VISUAL = source.LEARNINGTYPE_VISUAL,
            target.LEARNINGTYPE_AURAL = source.LEARNINGTYPE_AURAL,
            target.LEARNINGTYPE_KINESTHETIC = source.LEARNINGTYPE_KINESTHETIC,
            target.LEARNINGTYPE_READWRITE = source.LEARNINGTYPE_READWRITE
    WHEN NOT MATCHED THEN
        INSERT (ID, USERNAME, PASSWORD, EMAIL, DARK_MODE, DE_EN, CONTRAST,
                FONT_SIZE, EYE_TRACKING, COLOR_BLINDNESS, SIGN_LANGUAGE, ROLE,
                LEARNINGTYPE_VISUAL, LEARNINGTYPE_AURAL, LEARNINGTYPE_KINESTHETIC, LEARNINGTYPE_READWRITE)
            VALUES (-1, NULL, NULL, NULL, FALSE, FALSE, FALSE, 0, FALSE, 0, FALSE, 'ANONYMOUS', 0, 0, 0, 0);